{% set name = "libcpptraj-dev" %}
{% set version = os.getenv('VERSION', '4.3.3') %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  features:              [win]
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

source:
  path: ../

requirements:
  build:
    - python [win]
    - zlib
    - bzip2
    - libnetcdf [linux or win]
    - openblas [linux or win]
    - libgfortran [linux]
    - mingwpy [win]
    - gcc [linux]
  run:
    - zlib
    - bzip2
    - libnetcdf [linux or win]
    - openblas [linux or win]
    - libgfortran [linux]
    - gcc [linux]

test:
  commands:
    - cpptraj -h

about:
    home: https://github.com/amber-md/cpptraj/
    license: GPL v3
    summary: Biomolecular simulation trajectory/data analysis. 
