skip_commits:
  message: /\[circleci\]/

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"
    PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"
      ARCH: "64"

install:
  - rm C:\Program Files\Git\usr\bin\mv.exe
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda update conda -y
  - conda install conda-build -y
  - conda create -n py34 python=3.4 -y
  - activate py34
  - conda config --add channels conda-forge
  - conda install mingwpy -y
  - python -c "import sys; print(sys.prefix)"
  - python --version
  - conda install bzip2 -y
  - which g++
  - which gfortran

build_script:
  - "%CMD_IN_ENV% bash configure -noreadline -nonetcdf -nobzlib -nomathlib -shared gnu"
  - "%CMD_IN_ENV% C:/msys64/usr/bin/make libcpptraj"
  - "%CMD_IN_ENV% C:/msys64/usr/bin/make"

test_script:
  - echo "nothing to test"
  - echo "hello"

after_build:
  - 7z a cpptraj-%APPVEYOR_BUILD_ID%.zip bin/* src/*.h lib/*

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
