skip_commits:
  message: /\[circleci\]/

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"
    PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"
      ARCH: "64"

install:
  - "sh -lc \"
     if [ ! -f /usr/local/lib/libnetcdf.a ]; then
       curl -fsS -o netcdf-4.3.3.zip ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.zip &&
       7z x netcdf-4.3.3.zip -o$APPVEYOR_BUILD_FOLDER > /dev/null &&
       cd $APPVEYOR_BUILD_FOLDER/netcdf-4.3.3 &&
       exec 0</dev/null &&
       ./configure --enable-static --disable-netcdf-4 --prefix=/usr/local/ --disable-dap &&
       make -r install;
     else
       echo 'Have Cached NetCDF';
     fi
  \""
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels conda-forge
  - conda update conda -y
  - conda update --all -y
  - conda install conda-build -y
  - python -c "import sys; print(sys.prefix)"
  - python --version

test_script:
  - "%CMD_IN_ENV% conda build netcdf433" 
  - "%CMD_IN_ENV% conda build recipe" 

build: false
