{% set version = "4.4.1.1" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 7f040a0542ed3f6d27f3002b074e509614e18d6c515b2005d1537fec01b24909
  patches:
    - dfile.c.patch  # [win]
    - dim.c.patch  # [win]
    - semantics.c.patch  # [win]

requirements:
  build:
    - python  # [win]
    - cmake
    - pkg-config  # [unix]
    - msinttypes  # [win]
    - mingwpy # [win]
    - m2-m4 # [win]
    - curl
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
  run:
    - curl
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
    - mingwpy # [win]

test:
  commands:
    - nc-config --all  # [unix]
    - test -f ${PREFIX}/lib/libnetcdf.a  # [unix]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    #- conda inspect linkages -p $PREFIX libnetcdf  # [not win]
    #- conda inspect objects -p $PREFIX libnetcdf  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

extra:
  recipe-maintainers:
    - hainm
