{% set name = "openblas" %}
{% set version = os.getenv('VERSION', 'v0.2.19') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/openblas/v0.2.19/OpenBLAS-v0.2.19-Win64-int32.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopenblas%2Ffiles%2Fv0.2.19%2F&ts=1482273849&use_mirror=superb-dca2
  fn: OpenBLAS-v0.2.19-Win64-int32.zip

about:
    home: https://github.com/amber-md/cpptraj/
    license: GPL v3
    summary: Biomolecular simulation trajectory/data analysis. 
